---
micronaut:
    application:
        name: server
    server:
        port: 8082
        cors:
            enabled: true
---
consul:
  client:
    registration:
      enabled: false
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---
micronaut:
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
